# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181129_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/static/img/default.png', upload_to='./avatar/'),
        ),
    ]
